export const CLIENT_NAME_ENG = 'Malaghe'
export const CLIENT_NAME_FA = 'ملاقه'
export const CLIENT_VERSION = '۱.۰'
export const CLIENT_COPYRIGHT = ' کپی‌رایت © ۲۰۲۲'
export const CLIENT_DESCRIPTION = 'راهکارهای صنعتی آشپزخانه'
