apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: apakhbari/store
          env:
            - name: MONGO_URI
              value: 'mongodb://store-mongo-srv:27017/store'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: store-srv
spec:
  selector:
    app: store
  ports:
    - name: store
      protocol: TCP
      port: 3000
      targetPort: 3000
